[ADD] orders 기능 구현
wecode-bootcamp-korea/41-1st-IWEA-backend pull request #12
Opened 2023-01-10 04:34 UTC by yeyunny

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
orders API 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
post - addOrder : 장바구니에 있던 상품들이 결제 후 orders 테이블로 이동, order_status를 주문완료로 변경, 해당 사용자의 결제 금액만큼 포인트 차감
get - orderList : 해당 사용자가 지금까지 주문한 목록 조회
patch - cancelOrder : 주문 취소 후 order_status를 주문 취소로 변경, users 포인트 반환

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
3. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. 
**post - addOrder**
장바구니에 있던 상품들이 orders 테이블로 이동 / order_status 주문완료로 변경 / user 포인트 차감
![스크린샷 2023-01-10 오후 1 24 35](https://user-images.githubusercontent.com/110670796/211461652-64e67ff6-b938-4595-96b3-85354480ed90.png)
(1이 주문완료입니다)

**get - orderList**
해당 사용자가 지금까지 주문한 목록 조회
![스크린샷 2023-01-10 오후 1 31 11](https://user-images.githubusercontent.com/110670796/211462449-f6df8db0-5b1d-4c76-98b5-6f418fc534f3.png)

**patch - cancelOrder**
주문 취소 후 order_status를 주문 취소로 변경
![스크린샷 2023-01-10 오후 1 32 06](https://user-images.githubusercontent.com/110670796/211462545-20ae922f-53d8-4731-9a75-1fad1b4a9739.png)
(7이 주문 취소입니다)

users 포인트 반환
![스크린샷 2023-01-10 오후 1 32 43](https://user-images.githubusercontent.com/110670796/211462610-645b2084-26f1-4cc0-9006-43e1836567ea.png)

5. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-01-10 04:36 UTC, yeyunny commented on models/orderDao.js
> +// user points 찾는 쿼리
주석은 호준님께서 확인하신 후에 지우도록 하겠습니다!

2023-01-10 08:34 UTC, bigfanoftim requested changes
<img width="221" alt="image" src="https://user-images.githubusercontent.com/62135254/211500991-31dabdb3-a713-4060-8812-ccf9679a71b0.png">

이 파일 `.gitignore`에 추가해주세요!
이미 트래킹되었으니 cache remove 작업 후 add commit 하시면 없어질거에요!

2023-01-10 14:43 UTC, bigfanoftim requested changes

2023-01-10 14:43 UTC, bigfanoftim commented on services/orderService.js
> +  }
이렇게 사용되는 예외처리가 꽤나 많을텐데 간단하게나마 함수로 바꿔서 활용해보면 어떨까요?

```JavaScript
// src/utils/error.js
const throwCustomError(message, statusCode) => {
  const err = new Error(message);
  err.statusCode  = statusCode
  throw err
}

module.exports = { throwCustomError }
```
```JavaScript
// src/service/someService.js
const { throwCustomError } = require("../../utils/error")

if (userInfo.points - totalPrice < 0) throwCustomError("NOT_ENOUGH_POINTS!", 400)
```

2023-01-10 14:43 UTC, bigfanoftim commented on models/orderDao.js
> +  orderDone: 1,
```suggestion
  ORDER_DONE: 1,
```
enum value는 전부 `위와같은 형태(ALL_CAPS)`로 네이밍해주시면 좋을 것 같습니다!

2023-01-10 14:43 UTC, bigfanoftim commented on models/orderDao.js
> +  cash: 3,
여기도 마찬가지입니다!

2023-01-10 14:43 UTC, bigfanoftim commented on models/orderDao.js
> +  console.log("params", userId, cartId, products, totalPrice);
```suggestion
```
불필요한 로깅인 것 같아요!

2023-01-10 14:43 UTC, bigfanoftim commented on models/orderDao.js
> +    const orderId = idData["LAST_INSERT_ID()"];
```JavaScript
    const ... = await queryRunner.query(`
      INSERT INTO orders (
        user_id, 
        order_status_id
      ) VALUES (
        ${userId}, 
        ${OrderStatusId.orderDone}
      )
    `);
```
보통 INSERT문을 실행하면 결과로 inserId를 받을 수 있으니
한번 확인해보시는게 좋을 것 같아요!

또한 `?`는 prepared statements, SQL Injection과 관련된 것인데 userId또한 Enum value와 마찬가지로
SQL Injection과 상관없는 부분이니 알아보기 쉽게 위와 같이 작성해 볼 수 있을 것 같네요!

2023-01-11 02:06 UTC, bigfanoftim approved these changes
LGTM 👍

2023-01-11 02:06 UTC, merged